### ISSUE TITLE
[Java] The declared package "com.github.****" does not match the expected package ""

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#274]
I try to make a library for the first time in VSCode (I have done this before in IntelliJ and Eclipse).
My workspace looks like this:
<img width="238" alt="screen shot 2017-08-08 at 21 40 19" src="https://user-images.githubusercontent.com/738650/29091262-a19970ee-7c82-11e7-8729-5f43ca1d8256.png">

In LemmingsWalker.java I have: `package com.github.lemmingswalker;`.
Which gives me the following error:

> [Java] The declared package "com.github.lemmingswalker" does not match the expected package ""

##### Environment
- Operating System: Mac OSX
- JDK version: jdk1.8.0_144
- Visual Studio Code version: Version 1.14.2 (1.14.2)
- Java extension version: 0.8.0

**Comment by fbricon** [comment]
Do you have a sample project reproducing the error?

**Comment by clankill3r** [comment]
I figured out what it is (still seems like a bug).
I wanted to make a sample project so made a copy of the directory. While opening this in VSCode the error was gone.

If I rename the original directory the error is gone as well. If I rename it back to what it was the error comes back again. So I assume there is a bug in the cache validation?

**Comment by fbricon** [comment]
Yeah kinda, probably. 
If you could provide a sample project, that'd help us figure out exactly what the issue is.

**Comment by clankill3r** [comment]
Well here it is:
www.doekewartena.nl/temp/Remake2.zip

But it won't help. I only have the bug when the path is `/Volumes/DATA/lemmings_walker/Remake2`. If I rename `Remake2` or if I move the folder the problem is solved.

**Comment by fbricon** [comment]
Ok so it seems whenever you create a new java file, it's linked to the default package initially. Once you add the package declaration to that java file, the linked resource behind the scene should be updated to the proper package.

**Comment by fbricon** [comment]
@snjeza: can you see if we could link the parent folder to the default project instead of creating a linked resource to the file. That'd make all files in the folder/package automatically available to the classpath, instead of having to open each one of them manually (i.e the current fake compilation unit hack)

**Comment by snjeza** [comment]
@fbricon I will try

**Comment by gorkem** [comment]
@snjeza can we close this one?

**Comment by snjeza** [comment]
@gorkem I don't have a permission to do it.

**Comment by gorkem** [comment]
@snjeza oops. Fixed you should be able to do it now.

**Comment by fbricon** [comment]
When you open a standalone java file in a random directory (i.e, that doesn't belong to a project), if the class has a `foo.bar` package, that package name will be used by default. Now if you rename the package name and save, then the same error shows up (`The declared package "foo.bar.toto" does not match the expected package "foo.bar"`)

**Comment by snjeza** [comment]
@fbricon 
The issue hasn't been caused by this PR. See https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java#L195
I am not sure how to fix this issue except to recreate a link for such a file whenever resolving a compilation unit.

**Comment by Vanir112** [comment]
@fbricon Unfortunately it seems like this is still very much an issue, exactly like @clankill3r my package declaration is returning an error of ``The declared package "aprogrammerisneverlate.xtrex" does not match the expected package ""`` despite having a correct file tree to support it.

![image](https://user-images.githubusercontent.com/36479515/36208938-48756d10-1192-11e8-8b3f-f6357f14810c.png)

![image](https://user-images.githubusercontent.com/36479515/36208976-60995d2a-1192-11e8-90e4-ec601d52c794.png)


- Windows 10 Creator's Update
- JDK1.8.0_162
- VSCode version 1.2.0

**Comment by fbricon** [comment]
@Vanir112 given you have class files mixed with your source code, that tells me you're not using Maven or Gradle to build your code. As a consequence your source folders are not recognized and vscode-java gives you incorrect diagnostics. Can you try to use either Maven or Gradle (which is a good thing to do either way)

**Comment by clankill3r** [comment]
I did use maven. If I remember correct I fixed the problem with
reinstalling vscode.

2018-02-14 15:59 GMT+01:00 Fred Bricon <notifications@github.com>:

**Comment by james-sullivan** [comment]
<img width="563" alt="Annotation 2019-09-17 225947" src="https://user-images.githubusercontent.com/5818514/65110771-13febd80-d99f-11e9-948f-06e26e44fdc0.png">
I'm having a similar problem. Seemingly at random it just stops recognizing the packages. I tried reinstalling VS Code and the extensions, but it is still problem

**Comment by mordechaiSheinson** [comment]
I had the same error, check if you need to reload any of your extensions

**Comment by clankill3r** [comment]
Can you close vscode, remove the workspace storage and then open vscode, tell me if that fixed it.

**Comment by RickeyWard** [comment]
> <img alt="Annotation 2019-09-17 225947" width="563" src="https://user-images.githubusercontent.com/5818514/65110771-13febd80-d99f-11e9-948f-06e26e44fdc0.png">
> 
> I'm having a similar problem. Seemingly at random it just stops recognizing the packages. I tried reinstalling VS Code and the extensions, but it is still a problem

I have this same problem. I was editing a project for months, changed nothing but function bodies and now the extension is mad about the package names. It seems to have forgotten that maven expects main/java/ in the src root path. I haven't changed my pom.xml It just stopped working randomly. It tried deleting all the metadata for the project and letting them get recreated and it doesn't fix the issue.

the projects of course build find in maven

**Comment by jackHedaya** [comment]
I have been encountering this issue recently as well. My solution was to add 

```json
{
  "java.project.sourcePaths": [""]
}
```

to `.vscode/settings.json`.

**Comment by charlesAOC** [comment]
This was a problem for me too. I navigated to the configure class path tab through the "java projects" tab at the bottom left of the screen. From there, i removed all other paths apart from the default. this solved my problem. The "java.project.sourcePaths": [""]" solution does this.

**Comment by jheinem1** [comment]
This is still a problem regardless of what I set my `sourcePaths` setting to in Gradle projects. It seems the setting is completely ignored in my case.

**Comment by akarampetsos** [comment]
Just in case anyone has made the same (stupid) mistake that I did and cost me around 1 hour fumbling around like . Make sure your folder structure is "some/random/package" and don't create the folder "some.random.package" mechanically like me. I was convinced it was a cache issue because of the `expected package ""` in the error message.
