### ISSUE TITLE
1.42.0 with Lombok @Builder does not work with records

### ISSUE THREAD

**Issue by tienipia** [redhat-developer/vscode-java#4050]
Hi.
I've got jsut update vscode-java 1.41.1 to 1.42.0

before update, it's okay, 

![Image](https://github.com/user-attachments/assets/69aef6af-943d-457c-8821-3c5f42c873e4)
```java
import io.tienipia.model.Template;
import java.util.List;
import lombok.Builder;

@Builder
record TemplateResponse(List<Template> templates) {}
```

but after upgrade to 1.42.0

![Image](https://github.com/user-attachments/assets/e0475f92-c710-4822-b214-082a564bd33b)

```
The constructor TemplateResponse() is undefinedJava(134217858)
```

It occurs every vscode with 1.42.0

of course, manual build with maven works fine.
```
mvn clean compile
```

**Comment by jdgc12** [comment]
I've the same issue in v1.42.0

**Comment by philipfong** [comment]
I wish I found this before completely uninstalling and reinstalling vs code. I rolled back the extension to the previous stable and things are back to normal.

**Comment by linusbrimstedtellos** [comment]
Seems to be there in prerelease 1.43.2025051708 as well.

**Comment by logslie** [comment]
The same problem happens to me after updating vscode from 1.98 to 1.100.2 in Kali linux.

**Comment by shalska** [comment]
I have the same issue v1.42.0

**Comment by ankurkesharwani** [comment]
Same is happening for me. I am using VSCode Version: 1.100.2 (Universal). 
I also tried providing my own lombok.jar using java.jdt.ls.vmargs but it did not work.

This broke my entire workflow, have to resort to using IntelliJ.

**Comment by adolfo-cia** [comment]
Same issue here. Rolled back to 1.41.1 fixed it.

**Comment by danedb** [comment]
We were using @With with records and it also broke with 1.42.0. Rollback to 1.41.1 worked.

**Comment by DylanMerigaud** [comment]
Thanks a bunch @pastouret !

**Comment by JamesChen407** [comment]
Same here, have to downgrade to make it work. PLZ fix it

**Comment by okeylanders** [comment]
Same here; also couldn't use any of the ide tools to compile, run unit or integration tests. rolling back to 1.41.1 fixed the linter, compile, and test explorer runner.

**Comment by rgrunber** [comment]
I've built Lombok from their development branch, with the PR from https://github.com/projectlombok/lombok/pull/3888 applied. It can be accessed at https://github.com/rgrunber/lombok/releases/download/pull-3888/lombok-1.18.39.jar ( https://github.com/rgrunber/lombok/releases/tag/pull-3888 ) . From what I can tell, it should solve the issue. People are free to try it out and confirm. There's a few ways to do this, after updating to vscode-java 1.42.0 :

### Option 1 : Use in place of your existing project's Lombok library.

If Lombok is referenced in the configuration of your build tools (eg. pom.xml, build.gradle), you'll have to install it first so your build system can detect it.

For a Maven project :

```
$ mvn install:install-file -Dfile=/home/user/Downloads/lombok-1.18.39.jar -DgroupId=org.projectlombok -DartifactId=lombok -Dversion=1.18.39 -Dpackaging=jar
```

After that you can update your pom file(s) to refer to Lombok 1.18.39. Finally, when you load your project, you just need to make sure to "Use Project's Version" over the extension's and reload the project.

![Image](https://github.com/user-attachments/assets/d5e7a924-cf86-4206-9326-f42e4098f060)

![Image](https://github.com/user-attachments/assets/15908e66-62a2-4030-afad-7530d4b8805d)

### Option 2 : Replace vscode-java's embedded lombok library

vscode-java provides a version of Lombok and it is used when Lombok is detected on the classpath. You can always switch to your own project's Lombok version (see above), but this is the default one.

`~/.vscode/extensions/redhat.java-1.42.0-${platform}/lombok/lombok-1.18.36.jar`

If you move the new jar into this location :

```
rm ~/.vscode/extensions/redhat.java-1.42.0-linux-x64/lombok/lombok-1.18.36.jar
mv ~/Downloads/lombok-1.18.39.jar ~/.vscode/extensions/redhat.java-1.42.0-linux-x64/lombok/
```

then your vscode-java extension will now use that by default which should fix any issues. You would just need to confirm your project is set to "Use Extension's Version" and not the project's version.

**Comment by barrenaedu** [comment]
I can confirm the @rgrunber fix is working fine in Eclipse 2025-06. My installation steps also were:

1. Copy lombok-1.18.39.jar into eclipse directory.
2. Replace in eclipse.ini the entry:
`-javaagent:/opt/apps/eclipse/plugins/org.projectlombok.agent_1.18.38/lombok.jar`
for the line
`-javaagent:/opt/apps/eclipse/lombok-1.18.39.jar`
3. Restart eclipse

Thank you

**Comment by rgrunber** [comment]
I've embedded the development version of Lombok (towards 1.18.39) along with the PR that fixes this issue into vscode-java, rather than using a released (1.18.38) version that lacks the fix. This should resolve the issue in pre-releases and the upcoming 1.43.0 release without needing to perform any of the steps at https://github.com/redhat-developer/vscode-java/issues/4050#issuecomment-2955782487 .

**Comment by tienipia** [comment]
This must come as a huge relief for many developers who either struggled with this issue or weren’t even aware of the cause. Thank you for resolving it — your work is truly appreciated. @rgrunber

**Comment by stefanrybacki** [comment]
Can there be some kind of lombok interoperability testing establish before releasing a plugin update? This happens ever so often.

**Comment by dsokal** [comment]
Hi! I've just upgraded to 1.43.0 released yesterday, but I'm still experiencing similar issues with Lombok. I tried two Lombok versions - the extension's one and the one from my project. I'm getting similar compilation errors again. Can anyone confirm 1.43.0 resolved the issue? 🤔

**Comment by Maze-fr** [comment]
It's OK for me with 1.43 version (I was using pre-release until today and switch to release this morning).

![Image](https://github.com/user-attachments/assets/16c3e0c8-24db-413e-81c6-a570d27fffdd)

**Comment by ericwill** [comment]
> Can there be some kind of lombok interoperability testing establish before releasing a plugin update? This happens ever so often.

This is the responsibility of the Lombok project. Lombok uses internal Eclipse JDT APIs which change from time to time, when using such internal code it is important to monitor changes upstream and adapt to them proactively. The fact that a [PR fixing this issue](https://github.com/projectlombok/lombok/pull/3888) in Lombok itself has remained un-merged for a month points to a larger issue of inactive maintenance from Lombok's side.

**Comment by stefanrybacki** [comment]
@ericwill as I understood the comment from rgrunder lombok is also shipped with vscode-java in a version that is causing this issue.

**Comment by ericwill** [comment]
That was done as one-time effort to resolve user complaints because the Lombok project maintainers are slow to react (the [PR](https://github.com/projectlombok/lombok/pull/3888) to fix the issue in Lombok is still open!). VS Code Java does not maintain Lombok.

**Comment by stefanrybacki** [comment]
@ericwill got you, if there just would exist a lombok alternative
