### ISSUE TITLE
Building Java project shows error: "Build failed, do you want to continue?"

### ISSUE THREAD

**Issue by niiiksh** [redhat-developer/vscode-java#495]
Building Java project shows error: "Build failed, do you want to continue?" when the build is actually completed because when I click "Proceed" it will run updated version of my code and autobuild enabled when I type new code.
[javatest.zip](https://github.com/redhat-developer/vscode-java/files/1881660/javatest.zip)

##### Environment
- Operating System: Windows 10 Pro (1709)
- JDK version: 9.0.4
- Visual Studio Code version: 1.21.1
- Java extension version: 0.22.0

##### Steps To Reproduce
1. Open attached java project in Visual Studio Code with Java Extensions Pack installed
2. Start debugging by F5

[javatest.zip](https://github.com/redhat-developer/vscode-java/files/1881675/javatest.zip)

[.log](https://github.com/redhat-developer/vscode-java/files/1881706/default.log)

##### Current Result
Build error
##### Expected Result
No error
##### Additional Informations
I have another project built with this extension and it builds without any error.

**Comment by fbricon** [comment]
this sample projects builds without errors. I can run the Main class, although it stops because it can't connect to the socket, but that's irrelevant to this problem.

The log you attached references a bunch of classes that are not present in your sample. 

```
message: Helper cannot be resolved;code: 570425394
message: Device cannot be resolved to a type;code: 16777218
message: ClientThread cannot be resolved to a type;code: 16777218
message: ClientThread cannot be resolved to a type;code: 16777218
message: Constants cannot be resolved to a type;code: 16777218
message: Constants cannot be resolved to a type;code: 16777218
message: Constants cannot be resolved to a type;code: 16777218
message: Constants cannot be resolved to a type;code: 16777218
message: Constants cannot be resolved to a type;code: 16777218
message: Constants cannot be resolved to a type;code: 16777218
message: Constants cannot be resolved to a type;code: 16777218
message: Constants cannot be resolved to a type;code: 16777218
message: ClientThread cannot be resolved to a type;code: 16777218
message: ClientThread cannot be resolved to a type;code: 16777218
message: ClientThread cannot be resolved to a type;code: 16777218
message: Helper cannot be resolved;code: 570425394
message: Device cannot be resolved to a type;code: 16777218
message: Constants cannot be resolved to a variable;code: 33554515
message: ClientThread cannot be resolved to a type;code: 16777218
message: ClientThread cannot be resolved to a type;code: 16777218
message: ClientThread cannot be resolved to a type;code: 16777218
message: ClientThread cannot be resolved to a type;code: 16777218
message: Device cannot be resolved to a type;code: 16777218

```

Are those classes yours?
Have you tried [cleaning up the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)?

**Comment by niiiksh** [comment]
This is all the classes from my another project. I don't know why they are here, maybe they compiled in shared folder but that was unwanted behavior.

**Comment by ovidiup13** [comment]
Any updates on this? I am having the same issue. 

Builds fine from the command line. It's only when running VS Code Debug this occurs.

**Comment by jtuttas** [comment]
Same problem here (works perfect in the past, but this problem occures weeks ago by an update!)

**Comment by leandevesa-despegar** [comment]
Same problem here, hadnt made any changes to the project.
Building without problemas in IntelliJ

**Comment by leandevesa-despegar** [comment]
Ok, cleaning workspace seems to have fixed it (at least by now).
Can't provide sample project!

Thanks for your help

**Comment by ovidiup13** [comment]
@fbricon That seems to have solved it for me as well!

I don't have a sample project to share unfortunately. 

However, I think this issue appeared right after update to VS Code 1.22.1

**Comment by jtuttas** [comment]
I've deleted the complete workspaceStorage but the problem still there. Attached you will find a small Test Project where the error appears.

![error](https://user-images.githubusercontent.com/3327742/39033933-b0f4caa6-4474-11e8-890c-6f88968f5c48.PNG)

Well after pressing "Proceed" the code executed normal!

[Fiae16i.zip](https://github.com/redhat-developer/vscode-java/files/1930973/Fiae16i.zip)

**Comment by jtuttas** [comment]
Ok, solved it, the problem caused by a compile error in the Java Code. If I compile the code on the terminal the error was reported and I can fix it.

But why are compile errors not reported by the extension in the problem tab !?!?!

**Comment by ovidiup13** [comment]
Yeah, I couldn't find any logs whatsoever for the failed build process.

**Comment by rectcircle** [comment]
Get exactly the same error when I try to debug a Maven Java project of mine. "Build Failed".

"Build Failed" will not display when I save my workspace as a file

Temporary solution

`launch.json`
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Launch)-ProviderUserApplication<microservice-simple-provider-user>",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopOnEntry": false,
            "preLaunchTask": "package", //package before debug
            "mainClass": "com.itmuch.cloud.study.ProviderUserApplication",
            "projectName": "microservice-simple-provider-user",
            "args": ""
        }
    ]
}
```

`tasks.json`
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "package",
            "type": "shell",
            "command": "mvn package",
            "group": "build"
        },
        {
            "label": "test",
            "type": "shell",
            "command": "mvn -B test",
            "group": "test"
        }
    ]
}
```

**Comment by scriptwang** [comment]
Maybe your code has error,check it here.This is my case.
![snipaste_2018-05-18_08-39-09](https://user-images.githubusercontent.com/19930877/40210393-417d3d16-5a77-11e8-8a01-d3ad4e76a135.png)

**Comment by davidaorr** [comment]
I am getting this same error. I have a maven project that builds fine from the command line, and if I press the "Proceed" button will debug correctly.

**Comment by michaelkleinhenz** [comment]
Same here. Cleaning up the workspace did not help. Project compiles fine on command line. No errors shown on the trace console in vscode.

**Comment by rectcircle** [comment]
The extension only compile when I modify code file and save the file?
when I press `F5` to debug, the extension doesn't check and compile.

1. open a spring boot project(maven)
![image](https://user-images.githubusercontent.com/18106246/40540074-6e01d428-6049-11e8-9fee-44fbd38421c4.png)

2. clean the project to delete `target` directory
![image](https://user-images.githubusercontent.com/18106246/40540103-896bbbca-6049-11e8-9c17-06bcfae53d42.png)
![image](https://user-images.githubusercontent.com/18106246/40540122-9a696e5e-6049-11e8-8b72-7d68f7c5ac4f.png)

3. press `F5` to debug  , can't run and not `target` directory create
![image](https://user-images.githubusercontent.com/18106246/40540194-dc176234-6049-11e8-9e46-c08efe7e1e5c.png)

4.when I open a file to modify and save , `target` directory create, but only compile one file. other file no compile.
![image](https://user-images.githubusercontent.com/18106246/40540254-0b79ac62-604a-11e8-82a3-49f4e7ad2b4c.png)
![image](https://user-images.githubusercontent.com/18106246/40540266-189c2230-604a-11e8-8d71-05b0a91b9ac7.png)

5.use maven to compile like it
![image](https://user-images.githubusercontent.com/18106246/40540430-ba7ebe50-604a-11e8-9700-ee3d7811791f.png)

==============
I hope extension should check and compile project when we open project or debug

**Comment by Theodosia1005** [comment]
Same Problem.
The project is https://github.com/swagger-api/swagger-codegen
mvn complie success, but get error when debug
![image](https://user-images.githubusercontent.com/16056082/40541204-6afd9cc2-604d-11e8-863f-6bc18588b2c0.png)
Maven and jdk version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-25T03:49:05+08:00)
Maven home: C:\apache-maven-3.5.3\bin\..
Java version: 1.8.0_172, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_172\jre
Default locale: en_US, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by winstars** [comment]
Same Problem too.
Yet it looks like to be fixed on my problem.
1.I tried to change the jdk.home path from jdk10 to jdk 8, and it works fine!!!!
2.I have tried to clean the workspace before, but nothing changed.
3.maven on my vscode is working fine, compiling is also good, but vscode java debug is always failed.

**Comment by 3urdoch** [comment]
I have been tearing my hear out with this issue, **clearing the workspace** has fixed it for me. 

I was getting lots of errors related to another project. I can't recall but the other project was a project i used as a template for this one, so it was either that those files were at one time in the workspace and were no-longer, or I had previously opened that project with VS code.

Either way, that the time, the files were not in the workspace any more but the build was showing errors relating to them, deleting the workspace completely solved the issue but its obviously not a permanent fix as it could return. It seems the workspace is keeping residual class/java files behind that are no-longer relevant.

For now, I can continue without the build error. So i'm happy. 👍

**Comment by dsyer** [comment]
Is the wiki out of date? The "cleaning the workspace" instructions don't seem to make sense any more (there's nothing that says "Executing ..." anywhere in the developer tools console).

**Comment by dsyer** [comment]
Thanks. I can see the workspace storage directories, but I don't have a way to know which one is relevant to my current workspace. Also, maybe you could clarify what "clean" means? Is it literally just "delete the whole directory"?

**Comment by fbricon** [comment]
@dsyer it's indeed hard to see which one corresponds to your workspace. So the simplest is to delete the whole directory.

**Comment by fbricon** [comment]
but I guess we can change the directory naming scheme to add the current folder name as a suffix to the path hash, to make it easier to identify

**Comment by mgasparel** [comment]
I had the same issue, and was able to fix it by clearing my workspace directory.

**Comment by akshayeshenoi** [comment]
@dsyer @fbricon The instructions are indeed stale. However if you open the Java Language Server logs (`> Java: Open Java Language Server log file`), you can find `-data` flag somewhere in the file. 

Deleting everything in the `workspaceStorage/` folder did help. Make sure you reload your window after doing it though.

**Comment by yaohaizh** [comment]
@augustocdias What is your VSCode java version?

**Comment by augustocdias** [comment]
@yaohaizh sorry for taking too long to reply. I'm using the latest stable versions for all. All extensions updated and also latest stable VSCode

**Comment by yaohaizh** [comment]
@augustocdias Could you help share your server log for this issue?

**Comment by yaohaizh** [comment]
We have pushed a fix https://github.com/eclipse/eclipse.jdt.ls/commit/091dbb4ab5d17fb2c2d806e51974639fd7ae73bd  for this last week, not sure if this is related.

**Comment by dgolovin** [comment]
This issue is easy to replicate on windows. Cleaning up workspace helps sometimes but does not last, usually on second build attempt the issue returns. I am using v 0.32.0 on Windows 10.

**Comment by dgolovin** [comment]
This error seems to appear for me in case I have several maven projects with the same classes. Each maven project located in different folder and the folder then added to workspace,

**Comment by bottleIsEmpty** [comment]
Still have the same error. Cleaning workspaseStorage doesn't help. Debugger always says that 

> Error: Could not find or load main class com.alexandrbobko.customs.CustomsApplication

When I try to compile and run through console, it works perfectly fine.
The project repository: https://gitlab.com/alexandrbobko/customs/tree/master/server

**Comment by yaohaizh** [comment]
@alexeykazakov What's your vscode & vscode java extension version?

**Comment by satnav** [comment]
The first time I added a Java project to my workspace, a pop-up came up asking if I wanted to exclude extension-generated project settings files (.project, .classpath, .factorypath, .settings) from the file explorer. I clicked Yes, for this workspace (or something similar). After I kept getting the build error message, I tried the following:

I [cleaned the workspace](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory), then created a fresh workspace. I added a Java project to it, and when the popup came up, I selected Never. I then ran the debugger and I no longer got the message.

**Comment by john-dev** [comment]
I see this problem a lot of times.
Is it possible to skip the check somehow?
In 99% of the time, everything is actually fine..

Disabling it would help for now..

**Comment by testforstephen** [comment]
@john-dev Change the user setting  to`"java.debug.settings.forceBuildBeforeLaunch": false`, which will disable the check before run/debug.

**Comment by john-dev** [comment]
oh i was looking for that setting, thanks @testforstephen

**Comment by colin-young** [comment]
I am able to reliable reproduce this problem by having both Maven and Gradle build files present in the solution. If I remove the gradle files (just by renaming them to bak.*) and perform a "Java: Clean the java language server workspace" and restarting, the issue goes away. Re-introducing the gradle files triggers the issue again.

I don't know enough (yet) about the maven or gradle, or the VS Code java extensions to understand why or if there is a way to allow both to co-exist peacefully.

**Comment by fbricon** [comment]
@colin-young Gradle project import takes precedence over Maven's. You can decide to disable the Gradle project import by adding `"java.import.gradle.enabled": false` to your .vscode/settings.json file

**Comment by AmineZAMANI** [comment]
Just verify that you already added the tag <package>jar</package> to your pom.xml

**Comment by dsyer** [comment]
Here's another data point. I had this "Build failed..." issue in a workspace that was running [Theia](https://github.com/eclipse-theia/theia) with (by mistake) both `@theia/java` and this extension (`vscode-java`) installed as a plugin. One of them tripped over the other the whole time, and in the end everything would work, but only after the annoying error message. Removing `@theia/java` and `@theia/java-debug` fixed it.

**Comment by TylerHsia** [comment]
For me, the problem was caused by other files in the open folder that could not compile.

**Comment by LokeshKarki** [comment]
So this issue was popping up in my recently installed vs code wih jdk 14 with a basic Hello World program too.
**I changed the directory and it is now working**, but with this written on it.

`cd 'e:\try'; & 'c:\Users\lkshk\.vscode\extensions\vscjava.vscode-java-debug-0.28.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-14.0.1\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:50466' '--enable-preview' '-XX:+ShowCodeDetailsInExceptionMessages' '-Dfile.encoding=UTF-8' '-cp' 'C:\Users\lkshk\AppData\Roaming\Code\User\workspaceStorage\0185ec8187bc148d9a8a20b77ca120e5\redhat.java\jdt_ws\try_7906d541\bin' 'Runner' 
so this is working perfectly`

**Comment by wjx0912** [comment]
same problem, does it fixed?

**Comment by him500** [comment]
My problem was that the promt showed build failed but if i click on proceed it work just fine. to remove the annoying promt all i did was:
Go to java extension pack-> click on any extension settings icon -> click extension settings 
-> uncheck (Java › Debug › Settings: Force Build Before Launch)

I hope this answer helps

**Comment by Zeba14** [comment]
Same problem , couldn't fix it

**Comment by DoganM95** [comment]
Damn, this issue is now over 2 years old, still getting notifications on this

**Comment by n614cd** [comment]
I am getting a buildpath incomplete error on a multi-project build on Quartz. 
Short version:

- Gradle build files
- java 11. 
- The build works from the command line using gradle
- No changes, and it works fine with IntelliJ. 
- Runtime works just fine
- Verified the correct version of quartz installed in the classpath; and all dependencies with exact versions used.

Same error posted above.. Has anyone found a way to debug or printout what the compiler is doing?

**Comment by snjeza** [comment]
@n614cd could you, please, attach a project example?

**Comment by n614cd** [comment]
@snjeza 

Unfortunately this is private code I am working with. I have tried to strip the project down multiple ways (such as removing the java source files). Once I strip the code from the project (I have tried to remove test code, all code, core libraries...). I am no longer getting the error.  Which leads me to believe that the problem is less likely with the build itself, and more likely with some hidden error. 
Hence why I am trying to work it now before it somehow raises an issue in production.

Tim

**Comment by theAnkitt** [comment]
I had the same issue but when i deleted the java file containing error in that same folder where current java file is, then warning disappeared. you can also try to delete the file or correct the code in the folder your are working in they error should disappear.

**Comment by Nicolamunozi** [comment]
> 

This solve my problem. In my case, I'm using Vscode for developing in Java. For previous configurations (when I was studing Python) VSCode did create a .history folder containing versions of the code. Deleting that folder I could solve the problem. 

Thanks!

**Comment by a-st** [comment]
@snjeza I manage to provide a sample project (like @n614cd) which showcases the issue. Please have a look at https://github.com/a-st/vscode-java-issue-495

After opening the project, vscode shows following problems
![image](https://user-images.githubusercontent.com/63122/199979030-3d530e55-3d30-460a-8be7-ade11bb08f05.png)

**Comment by snjeza** [comment]
@a-st This is an upstream buildship issue - https://github.com/eclipse/buildship/issues/1131
You can try the following patch:
```
diff --git a/app_a/build.gradle b/app_a/build.gradle
index def2540..2305e10 100644
--- a/app_a/build.gradle
+++ b/app_a/build.gradle
@@ -1,6 +1,7 @@
 plugins {
     id 'java'
     id "org.springframework.boot"
+    id "eclipse"
 }
 
 dependencies {
@@ -9,4 +10,19 @@ dependencies {
 
     implementation group: 'org.springframework.boot', name: 'spring-boot-starter', version: '2.7.5'
     testImplementation group: 'org.springframework.boot', name: 'spring-boot-starter-test', version: '2.7.5'
-}
\ No newline at end of file
+}
+
+eclipse {
+  classpath {
+    containsTestFixtures = true
+    file {
+        whenMerged {
+            cp -> cp.getEntries().forEach{
+                cpEntry -> if(cpEntry.kind=='src') {
+                    cpEntry.output = cpEntry.output.replace('bin/', 'build/classes/java/')
+                }
+            }
+        }
+    }
+  }
+}
diff --git a/module_a/build.gradle b/module_a/build.gradle
index aeb004d..92d39bc 100644
--- a/module_a/build.gradle
+++ b/module_a/build.gradle
@@ -1,6 +1,22 @@
 apply plugin: 'java-library'
+apply plugin: 'eclipse'
 
 dependencies {
     testImplementation project (':module_b').sourceSets.test.output
     testImplementation group: 'org.springframework.boot', name: 'spring-boot-starter-test', version: '2.7.5'
+}
+
+eclipse {
+  classpath {
+    containsTestFixtures = true
+    file {
+        whenMerged {
+            cp -> cp.getEntries().forEach{
+                cpEntry -> if(cpEntry.kind=='src') {
+                    cpEntry.output = cpEntry.output.replace('bin/', 'build/classes/java/')
+                }
+            }
+        }
+    }
+  }
 }
\ No newline at end of file
diff --git a/module_b/build.gradle b/module_b/build.gradle
index 20a07af..ab40b96 100644
--- a/module_b/build.gradle
+++ b/module_b/build.gradle
@@ -1,5 +1,21 @@
 apply plugin: 'java-library'
+apply plugin: 'eclipse'
 
 dependencies {
     testImplementation group: 'org.springframework.boot', name: 'spring-boot-starter-test', version: '2.7.5'
+}
+
+eclipse {
+  classpath {
+    containsTestFixtures = true
+    file {
+        whenMerged {
+            cp -> cp.getEntries().forEach{
+                cpEntry -> if(cpEntry.kind=='src') {
+                    cpEntry.output = cpEntry.output.replace('bin/', 'build/classes/java/')
+                }
+            }
+        }
+    }
+  }
 }
\ No newline at end of file
```
